config/routes.rb
GuiderCms::Engine.routes.draw do



  get '/guider_index', to: 'articles#index', as: 'guider_home'

  get '/category/new', to: 'categories#new', as: 'new_optimized_category'

  get '/your_articles', to: 'current_user_articles#index', as: 'user_articles'

  get '/your_articles/:root/:selected_category/:id', to: 'articles#show', as: 'user_article'

  get '/:root/create_new_subcategories', to: 'subcategories#new', as: 'new_subcategory'


  get '/root_categories', to: 'categories#index', as: 'root_categories'

  get 'categories/:id/edit', to: 'categories#edit', as: 'edit_categories'


  # :root_category/:category

  # get '/:root/:selected_category/:id/edit', to: 'articles#edit', as: 'edit_content'

  get '/move_higher/:id', to: 'articles#edit_article_position_one_backward', as: 'move_article_backward'

  get '/move_lower/:id', to: 'articles#edit_article_position_one_forward', as: 'move_article_forward'

  get '/:root/new', to: 'articles#new', as: 'new_content'


  get '/:root/:id/edit', to: 'articles#edit', as: 'root_content_edit'

  get '/:root/', to: 'articles#index', as: 'content_new_back'

  get '/:root/content/:id', to: 'articles#show', as: 'root_articles'

  get '/:root/:selected_category', to: 'articles#index', as: 'contents'


  get '/:root/:selected_category/:id', to: 'articles#show', as: 'content'

  get '/:root/:selected_category/:id/edit', to: 'articles#edit', as: 'edit_content'

  resources :categories

  resources :subcategories

  resources :articles

  get 'user_articles', to: 'current_user_articles#index'

end

app/models/guider_cms/application_record.rb
module GuiderCms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/guider_cms/application_controller.rb
module GuiderCms
  class ApplicationController < ::ApplicationController
    # rescue_from StandardError, :with => :render_404 
    # protect_from_forgery with: :exception
    layout 'application'


    def render_404
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end
end

app/controllers/guider_cms/articles_controller.rb
require_dependency "guider_cms/application_controller"

module GuiderCms
  class ArticlesController < ApplicationController
    layout GuiderCms.layout || 'application'
    include GuiderCms::ArticlesHelper
    before_action :set_article, only: [:edit, :update, :destroy, :edit_article_position_one_backward, :edit_article_position_one_forward]
    # before_action :is_guider_assesible, only: [:new, :edit, :update, :destroy]
    # before_action :is_correct_user, only: [:edit, :update, :destroy]
    # GET /articles


    def index
      @root = params[:root]
      @keyword = "home"
      @is_guider_admin = is_guider_admin
      @current_user = current_user
      @selected_category = params[:selected_category]
      if @root.nil?
        @root_category = Category.where(parent_id: nil).first
        if @root_category.nil?
          redirect_to new_optimized_category_path, alert: "Create a root category first"
        else
          @root = @root_category.classification
          if @selected_category.nil?
            @selected_category_class = @root_category
            @children_category = @root_category.children.order(:id)
          end
        end
      else
        @root_category = Category.find_by(classification: @root) || Category.find_by(slug: @root)
        if @selected_category.nil?
          @selected_category_class = @root_category
        else
          @selected_category_class = Category.find_by(classification: @selected_category) || Category.find_by(slug: @selected_category)
        end
        @children_category = @root_category.children.order(:id)
      end
      if @root_category.view_type == "menu" || @root_category.view_type == "ordered list"
        if @root_category.articles == [] && @root_category.children != []
          @selected_category_class = @root_category.children.first
        end
      end
      if @root_category.view_type == "ordered list" || @root_category.view_type == "ordered grid"
        if @root_category.children == []
          redirect_to new_optimized_category_path, notice: "Create a new category under #{@root_category.classification}"
        end
      end
      if @root_category.view_type == "blog grid" || @root_category.view_type == "blog list"
        @categories = category_options_array_for_article(nil, [], @root_category.id, 0)
        @articles_id = []

        @categories.each do |category|
          @required_category_class = Category.find_by(classification: category[0].gsub('&nbsp;', ''))
          @required_category_class.articles.each do |article|
            @articles_id.append(article.id)
          end
        end
        @articles = Article.where(id: @articles_id).order(updated_at: :desc).page params[:page]

        @keyword = "Latest"
        # @articles = Article.all.order(created_at: :desc).page params[:page]
      end
    end


    # GET /articles/1
    def show
      @article = Article.friendly.find(params[:id])
      @coming_from = params[:action_from]
      @root = params[:root]
      @selected_category = params[:selected_category]
      if Category.find_by(classification: @root).nil?
        @root_category = Category.find_by(slug: @root)
      else
        @root_category = Category.find_by(classification: @root)
      end
      if @selected_category.nil?
        @selected_category = @root
        @selected_category_class = @root_category
      else
        if Category.find_by(classification: @selected_category).nil?
          @selected_category_class = Category.find_by(slug: @selected_category)
        else
          @selected_category_class = Category.find_by(classification: @selected_category)
        end
      end
    end

    # GET /articles/new
    def new

      if current_user && is_guider_admin

        @root = params[:root]
        @article = Article.new
        if @root.nil?
          redirect_to guider_home_path
        else
          if Category.find_by(classification: @root).nil?
            @root_category = Category.find_by(slug: @root)
          else
            @root_category = Category.find_by(classification: @root)
          end
          @article.category = @root_category

        end
      else
        redirect_to content_new_back_path(root: @root_category.slug || @root_category.classification)
      end

    end

    # GET /articles/1/edit
    def edit
      if current_user && current_user.id != @article.author_id
        redirect_to guider_home_path
      else
        @root = params[:root]
        @categories = Category.all
        @selected_category = Category.friendly.find(@article.category_id)
        if @selected_category.parent.nil?
          @root_category = @selected_category
        else
          @root_category = @selected_category.ancestors.last
        end
      end
    end

    # POST /articles
    def create
      @categories = Category.all
      @article = Article.new(article_params)


      @selected_category = Category.find(@article.category_id)
      @root_category = @selected_category.ancestors.last

      @article.author_id = current_user.id

      if @article.save
        if @root_category.nil?
          redirect_to content_new_back_path(root: @selected_category.slug || @selected_category.classification)
        else
          redirect_to content_path(@article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category.slug || @selected_category.classification), notice: 'Article was successfully created.'
        end
        # redirect_to guider_home_path
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update

      category_id = @article.category_id
      if @article.update(article_params)
        if @article.category_id != ""
          req_category_id = @article.category_id
        else
          req_category_id = category_id
        end
        @selected_category_class = Category.find(req_category_id)
        @root_category = @selected_category_class.ancestors.last
        # redirect_to user_articles_path, notice: 'Article was successfully updated.'
        if @root_category.nil?
          redirect_to content_new_back_path(root: @selected_category_class.slug || @selected_category_class.classification)
        else
          redirect_to content_path(@article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug || @selected_category_class.classification), notice: 'Article was successfully created.'
        end

        # redirect_to guider_home_path

      else
        render :edit
      end
    end

    def edit_article_position_one_backward
      root = params[:root]
      selected_category = params[:selected_category]
      @article.move_higher
      if selected_category == ""
        redirect_to content_new_back_path(root: root)
      else
        redirect_to contents_path(root: root, selected_category: selected_category)
      end
    end

    def edit_article_position_one_forward
      root = params[:root]
      selected_category = params[:selected_category]
      @article.move_lower
      if selected_category == ""
        redirect_to content_new_back_path(root: root)
      else
        redirect_to contents_path(root: root, selected_category: selected_category)
      end
    end

    # DELETE /articles/1
    def destroy
      if @article.author_id == current_user.id or is_guider_admin
        @article.destroy
        redirect_to guider_home_path, notice: 'Article was successfully destroyed.'
      else
        redirect_to guider_home_path, alert: "Cannot do that"
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def is_correct_user
        @article = Article.find(params[:id])
        if current_user.id != @article.author_id
          redirect_to root_path
        end
      end

      def is_guider_assesible
        # puts(current_user)
        if current_user and is_guider_admin?
          redirect_to root_path
        end
      end

      def set_article
        if Article.friendly.find(params[:id]).nil?
          @article = Article.find_by(slug: params[:id])
        else
          @article = Article.friendly.find(params[:id])
        end
      end

      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :description, :body, :category_id, :author_id, :header_image, :root, :keywords)
      end
  end
end

app/controllers/guider_cms/categories_controller.rb
require_dependency "guider_cms/application_controller"

module GuiderCms
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]


    def index
      @all_categories = Category.all
      if @all_categories == []
        redirect_to new_optimized_category_path
      else
        @categories = Category.where(parent_id: nil)
        @root_category = Category.where(is_root_category: true).first
      end
    end

    def new
      if current_user && is_guider_admin
        @root = Category.where(is_root_category: true).first
        @category = Category.new
        @categories = Category.all
        @view_type = ["full grid", "blog grid", "blog list", "ordered list", "ordered grid", "normal grid with menu"]
        @root_categories = Category.where(is_root_category: true)
        # @root_categories = category_options_array()
      else
        redirect_to main_app.root_path, alert: "Not authorized"
      end
    end

    def edit
      if !(current_user)
        redirect_to guider_home_path
      else
        if !(is_guider_admin)
          redirect_to guider_home_path
        else
          @root_categories = Category.where(is_root_category: true)
          @view_type = ["full grid", "blog grid", "blog list", "ordered list", "ordered grid", "normal grid with menu"]
        end
      end
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to root_categories_path
      else
        render :new
      end
    end

    def update
      if @category.update(category_params)
        # if @category.update(category_params)
          redirect_to root_categories_path
      else
          render :edit
      end
    end

    def destroy
      if !!current_user && is_guider_admin
        if @category.articles == []
          @category.destroy
          @all_categories = Category.all
          if @all_categories != []
            redirect_to root_categories_path, notice: 'Categories was successfully destroyed.'
          else
            redirect_to guider_home_path
          end
        else
          redirect_to root_categories_path, alert: "Only Empty Categories can be deleted."
        end
      else
        redirect_to guider_home_path
      end
    end


    private
    def set_category
      @category = Category.friendly.find(params[:id])
      if @category.parent
        @root_id = @category.parent
      else
        @root_id = nil
      end
    end

    def category_params
      params.require(:category).permit(:classification, :parent_id, :view_type, :header_image, :slug)
    end
  end
end

app/controllers/guider_cms/current_user_articles_controller.rb
require_dependency "guider_cms/application_controller"

module GuiderCms
  class CurrentUserArticlesController < ApplicationController
    def index
      if current_user && is_guider_admin
        @articles = Article.where(author_id: current_user.id)
        @root = Category.where(is_root_category: true).first.classification
      else
        redirect_to guider_home_path
      end
    end
  end
end

app/controllers/guider_cms/subcategories_controller.rb
require_dependency "guider_cms/application_controller"

module GuiderCms
  class SubcategoriesController < ApplicationController
    def new
      if current_user && is_guider_admin
        @root = params[:root]
        @root_category = Category.find_by(classification: @root)
        @categories = Category.where(parent_id: @root_category.id)
      else
        redirect_to content_new_back_path(root: @root)
      end
    end

    def create
      classification = params[:subcategory]["category"]
      subcategory = params[:subcategory]["subcategory"]
      # puts(classification)
      #
      #
      category = Category.find_by(classification: classification)
      puts(category.id)
      category.children.create(classification: subcategory)

      @root = category.ancestors.last.classification

      redirect_to content_new_back_path(root: @root)
    end

    private
    def article_params
      params.require(:subcategory).permit(:category, :subcategory)
    end
  end
end

app/helpers/guider_cms/application_helper.rb
module GuiderCms
  module ApplicationHelper
    def method_missing method, *args, &block
   if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
     if main_app.respond_to?(method)
       main_app.send(method, *args)
     else
       super
     end
   else
     super
   end
 end

 def respond_to?(method)
   if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
     if main_app.respond_to?(method)
       true
     else
       super
     end
   else
     super
   end
 end

 def subcat_prefix(depth)
  ("&nbsp;" * 4 * depth).html_safe
 end

 def category_options_array_for_article(current_id = nil,categories=[], parent_id=nil, depth=0)
  if categories == []
    root = Category.find(parent_id)
    categories << [subcat_prefix(depth) + root.classification, root.id]
    category_options_array(current_id,categories, root.id, depth+1)
  end
  categories
end

def article_options(id)
  req_array = []
  Category.find(id)
end



 def category_options_array(current_id = nil,categories=[], parent_id=nil, depth=0)
    Category.where(parent_id: parent_id).order(:id).each do |category|
      categories << [subcat_prefix(depth) + category.classification, category.id]
      category_options_array(current_id,categories, category.id, depth+1)
  end
  categories
end

def title(text)
    content_for :title, text
end

def meta_tag(tag, text)
    content_for :"meta_#{tag}", text
end

def yield_meta_tag(tag, default_text='')
  content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
end

  end
end

app/helpers/guider_cms/articles_helper.rb
module GuiderCms
  module ArticlesHelper
    def category_options_array_for_article(current_id = nil,categories=[], parent_id=nil, depth=0)
     if categories == []
       root = Category.find(parent_id)
       categories << [subcat_prefix(depth) + root.classification, root.id]
       category_options_array(current_id,categories, root.id, depth+1)
     end
     categories
   end

   def article_options(id)
     req_array = []
     Category.find(id)
   end

   def subcat_prefix(depth)
    ("&nbsp;" * 4 * depth).html_safe
   end

    def category_options_array(current_id = nil,categories=[], parent_id=nil, depth=0)
     # Category.where('parent_id = ? AND id != ?', parent_id, current_id ).order(:id).each do |category|
     Category.where(parent_id: parent_id).order(:id).each do |category|
         categories << [subcat_prefix(depth) + category.classification, category.id]
         category_options_array(current_id,categories, category.id, depth+1)
     end

     categories
   end

  end
end

app/helpers/guider_cms/categories_helper.rb
module GuiderCms
  module CategoriesHelper  
  end
end

app/helpers/guider_cms/current_user_articles_helper.rb
module GuiderCms
  module CurrentUserArticlesHelper
  end
end

app/helpers/guider_cms/subcategories_helper.rb
module GuiderCms
  module SubcategoriesHelper
  end
end

app/views/guider_cms/articles/_articles.html.slim
- selected_category_class.articles.each do |article|
  .card style=("margin-bottom: 2vh;")
    - if article.header_image.attached?
      = image_tag(main_app.url_for(article.header_image), class: "card-img-top")
    - else
      - if article.body.embeds.find{|embeds| embeds.image?}
        = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), class: "card-img-top")
    .card-body
      - if selected_category_class.parent.nil?
        h4.card-title= link_to "# article.title ", root_articles_path(article, root: root_category.slug || root_category.classification), class: "grid-link"
      - else
        h4.card-title= link_to "# article.title ", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "grid-link"
      p.card-text
        = article.description[0..300].gsub(/\s\w+$/,'...')
      - if selected_category_class.parent.nil?
        = link_to "Read Now", root_articles_path(article, root: root_category.slug || root_category.classification), class: "btn btn-outline-primary"
      - else
        = link_to "Read Now", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "btn btn-outline-primary"

app/views/guider_cms/articles/_latest.html.slim
- articles.each do |article|
  .card style=("margin-bottom: 2vh;")
    - if article.header_image.attached?
      = image_tag(main_app.url_for(article.header_image), class: "card-img-top")
    - else
      - if article.body.embeds.find{|embeds| embeds.image?}
        = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), class: "card-img-top")
    .card-body
      - if selected_category_class.parent.nil?
        h4.card-title= link_to "# article.title ", root_articles_path(article, root: root_category.slug || root_category.classification), class: "grid-link"
      - else
        h4.card-title= link_to "# article.title ", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "grid-link"
      p.card-text
        = article.description[0..300].gsub(/\s\w+$/,'...')
      - if selected_category_class.parent.nil?
        = link_to "Read Now", root_articles_path(article, root: root_category.slug || root_category.classification), class: "btn btn-outline-primary"
      - else
        = link_to "Read Now", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "btn btn-outline-primary"

app/views/guider_cms/articles/_list_articles.html.slim
- selected_category_class.articles.each do |article|
  .card
    .row.no-gutters
      .col-md-6
        - if article.header_image.attached?
          = image_tag(main_app.url_for(article.header_image), style: "height:100%;width:100%;")
        - else
          - if article.body.embeds.find{|embeds| embeds.image?}
            = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), style: "height:100%;width:100%;")
      .col-md-6
        .card-body
          - if selected_category_class.parent.nil?
            h4.card-title= link_to "# article.title ", root_articles_path(article, root: root_category.slug || root_category.classification), class: "grid-link"
          - else
            h4.card-title= link_to "# article.title ", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "grid-link"
          p.card-text= article.description
          - if selected_category_class.parent.nil?
            = link_to "Read Now", root_articles_path(article, root: root_category.slug || root_category.classification), class: "btn btn-outline-primary"
          - else
            = link_to "Read Now", content_path(article, root: root_category.slug || root_category.classification, selected_category: selected_category_class.slug  || selected_category_class.classification), class: "btn btn-outline-primary"

app/views/guider_cms/articles/_list_latest.html.slim
- @articles.each do |article|
  .card style=("margin-bottom: 10px;")
    .row.no-gutters
      .col-md-6
        - if article.header_image.attached?
          = image_tag(main_app.url_for(article.header_image), style: "width:100%;")
        - else
          - if article.body.embeds.find{|embeds| embeds.image?}
            = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), style: "height:100%;width:100%;")
      .col-md-6
        .card-body
          - if @selected_category_class.parent.nil?
            h4.card-title= link_to "# article.title ", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "grid-link"
          - else
            h4.card-title= link_to "# article.title ", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "grid-link"
          p.card-text= article.description
          - if @selected_category_class.parent.nil?
            = link_to "Read Now", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "btn btn-outline-primary"
          - else
            = link_to "Read Now", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "btn btn-outline-primary"

app/views/guider_cms/articles/_ordered_grid.html.slim
- if @selected_category_class.articles == []
  center
    h2 No Content
    - if @current_user && @is_guider_admin
      h3 Click on New Content to create Content
- else
  .row
    .card-columns
      - @selected_category_class.articles.order(position: :asc).each do |article|
        .card style=("margin-bottom: 2vh;")
          - if article.header_image.attached?
            = image_tag(main_app.url_for(article.header_image), class: "card-img-top")
          - else
            - if article.body.embeds.find{|embeds| embeds.image?}
              = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), class: "card-img-top")
          .card-body
            - if @selected_category_class.parent.nil?
              h4.card-title= link_to "# article.title ", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "grid-link"
            - else
              h4.card-title= link_to "# article.title ", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "grid-link"
            p.card-text
              = article.description[0..300].gsub(/\s\w+$/,'...')
            - if @selected_category_class.parent.nil?
              = link_to "Read Now", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "btn btn-outline-primary"
            - else
              = link_to "Read Now", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "btn btn-outline-primary"
            - if @current_user && @is_guider_admin
              - if @selected_category_class.id == @root_category.id
                = link_to move_article_backward_path(article, root: @root_category.slug) do
                  = image_tag("guider_cms/up.png", height: "25")
              - else
                = link_to move_article_backward_path(article, root: @root_category.slug, selected_category: @selected_category_class.slug) do
                  = image_tag("guider_cms/up.png", height: "25")
              - if @selected_category_class.id == @root_category.id
                = link_to move_article_forward_path(article, root: @root_category.slug) do
                  = image_tag("guider_cms/down.png", height: "25")
              - else
                = link_to move_article_forward_path(article, root: @root_category.slug, selected_category: @selected_category_class.slug) do
                  = image_tag("guider_cms/down.png", height: "25")

app/views/guider_cms/articles/_ordered_list.html.slim
- @selected_category_class.articles.order(position: :asc).each do |article|
  .card style=("margin-bottom: 10px;")
    .row.no-gutters
      .col-md-6
        - if article.header_image.attached?
          = image_tag(main_app.url_for(article.header_image), style: "height:100%;width:100%;")
        - else
          - if article.body.embeds.find{|embeds| embeds.image?}
            = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), style: "height:100%;width:100%;")
      .col-md-6
        .card-body
          - if @selected_category_class.parent.nil?
            h4.card-title= link_to "# article.title ", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "grid-link"
          - else
            h4.card-title= link_to "# article.title ", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "grid-link"
          p.card-text= article.description
          - if @selected_category_class.parent.nil?
            = link_to "Read Now", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "btn btn-outline-primary"
          - else
            = link_to "Read Now", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "btn btn-outline-primary"
          - if @current_user && @is_guider_admin
            - if @selected_category_class.id == @root_category.id
              = link_to move_article_backward_path(article, root: @root_category.slug) do
                = image_tag("guider_cms/up.png", height: "25")
            - else
              = link_to move_article_backward_path(article, root: @root_category.slug, selected_category: @selected_category_class.slug) do
                = image_tag("guider_cms/up.png", height: "25")
            - if @selected_category_class.id == @root_category.id
              = link_to move_article_forward_path(article, root: @root_category.slug) do
                = image_tag("guider_cms/down.png", height: "25")
            - else
              = link_to move_article_forward_path(article, root: @root_category.slug, selected_category: @selected_category_class.slug) do
                = image_tag("guider_cms/down.png", height: "25")

app/views/guider_cms/articles/edit.html.slim
h1 Editing Article
= render 'form', article: @article
= link_to 'Back', contents_path(root: @root, selected_category: @article.category.classification)

app/views/guider_cms/articles/new.html.slim
h1 New Article
= render 'form', article: @article
br/
= link_to 'Back', content_new_back_path(root: @root)

app/views/guider_cms/articles/show.html.slim
- title @article.title
- meta_tag :description, @article.description
- meta_tag :keywords, @article.keywords
- if @article.header_image.attached?
  = image_tag(main_app.url_for(@article.header_image), width: "100%")
h1= @article.title
= raw @article.body
br/
- if current_user && current_user.id == @article.author_id
  - if @selected_category == @root
    = link_to 'Edit', root_content_edit_path(root: @root)
  - else
    = link_to 'Edit', edit_content_path(@article.id, root: @root, selected_category: @selected_category)
    | \
- if current_user && current_user.id == @article.author_id
  = link_to 'Delete', article_path(@article.id), method: :delete
  | \
- if request.original_url.include?('your_articles')
  = link_to "Back", user_articles_path
- else
  - if @selected_category == @root
    = link_to 'Back', content_new_back_path(root: @root)
  - else
    = link_to 'Back', contents_path(root: @root, selected_category: @selected_category)
br/
br/
- if @selected_category_class.articles.length > 1
  h3 Related contents
  .row
    .card-columns
      - @selected_category_class.articles.each do |article|
        - if article.id != @article.id
          .card style=("margin-bottom: 2vh;") 
            - if article.header_image.attached?
              = image_tag(main_app.url_for(article.header_image), class: "card-img-top")
            - else
              - if article.body.embeds.find{|embeds| embeds.image?}
                = image_tag(main_app.url_for(article.body.embeds.find{|embeds| embeds.image?}), class: "card-img-top")
            .card-body
              h5.card-title= article.title
              p.card-text
                = article.description[0..500].gsub(/\s\w+$/,'...')
              - if @selected_category_class.parent.nil?
                = link_to "Read Now", root_articles_path(article, root: @root_category.slug || @root_category.classification), class: "btn btn-primary"
              - else
                = link_to "Read Now", content_path(article, root: @root_category.slug || @root_category.classification, selected_category: @selected_category_class.slug  || @selected_category_class.classification), class: "btn btn-primary"